package calculator;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pixel
 */
public class CalculatorView extends javax.swing.JFrame {
    
    private String currentInput = "";
    private double firstNumber = 0;
    private String operator = "";

    /**
     * Creates new form CalculatorView
     */
    public CalculatorView() {
        initComponents();
        setTitle("Mi calculadora");
        display.setEditable(false);
        display.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonProduct = new javax.swing.JButton();
        buttonClean = new javax.swing.JButton();
        buttonZero = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        buttonDivision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 2000));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        display.setMinimumSize(new java.awt.Dimension(64, 50));
        display.setPreferredSize(new java.awt.Dimension(98, 50));
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        button1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button1.setText("1");
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setMaximumSize(new java.awt.Dimension(80, 80));
        button1.setMinimumSize(new java.awt.Dimension(80, 80));
        button1.setPreferredSize(new java.awt.Dimension(80, 80));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1);

        button2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button2.setText("2");
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.setMaximumSize(new java.awt.Dimension(80, 80));
        button2.setMinimumSize(new java.awt.Dimension(80, 80));
        button2.setPreferredSize(new java.awt.Dimension(80, 80));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel3.add(button2);

        button3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button3.setText("3");
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button3.setMaximumSize(new java.awt.Dimension(80, 80));
        button3.setMinimumSize(new java.awt.Dimension(80, 80));
        button3.setPreferredSize(new java.awt.Dimension(80, 80));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel3.add(button3);

        buttonPlus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonPlus.setText("+");
        buttonPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPlus.setMaximumSize(new java.awt.Dimension(80, 80));
        buttonPlus.setMinimumSize(new java.awt.Dimension(80, 80));
        buttonPlus.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });
        jPanel3.add(buttonPlus);

        button4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button4.setText("4");
        button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button4.setMaximumSize(new java.awt.Dimension(80, 80));
        button4.setMinimumSize(new java.awt.Dimension(80, 80));
        button4.setPreferredSize(new java.awt.Dimension(80, 80));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel3.add(button4);

        button5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button5.setText("5");
        button5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button5.setMaximumSize(new java.awt.Dimension(80, 80));
        button5.setMinimumSize(new java.awt.Dimension(80, 80));
        button5.setPreferredSize(new java.awt.Dimension(80, 80));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel3.add(button5);

        button6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button6.setText("6");
        button6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button6.setMaximumSize(new java.awt.Dimension(80, 80));
        button6.setMinimumSize(new java.awt.Dimension(80, 80));
        button6.setPreferredSize(new java.awt.Dimension(80, 80));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel3.add(button6);

        buttonMinus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonMinus.setText("-");
        buttonMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMinus.setMaximumSize(new java.awt.Dimension(80, 80));
        buttonMinus.setMinimumSize(new java.awt.Dimension(80, 80));
        buttonMinus.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });
        jPanel3.add(buttonMinus);

        button7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button7.setText("7");
        button7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button7.setMaximumSize(new java.awt.Dimension(80, 80));
        button7.setMinimumSize(new java.awt.Dimension(80, 80));
        button7.setPreferredSize(new java.awt.Dimension(80, 80));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel3.add(button7);

        button8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button8.setText("8");
        button8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button8.setMaximumSize(new java.awt.Dimension(80, 80));
        button8.setMinimumSize(new java.awt.Dimension(80, 80));
        button8.setPreferredSize(new java.awt.Dimension(80, 80));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel3.add(button8);

        button9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button9.setText("9");
        button9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button9.setMaximumSize(new java.awt.Dimension(80, 80));
        button9.setMinimumSize(new java.awt.Dimension(80, 80));
        button9.setPreferredSize(new java.awt.Dimension(80, 80));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel3.add(button9);

        buttonProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonProduct.setText("*");
        buttonProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonProduct.setMaximumSize(new java.awt.Dimension(80, 80));
        buttonProduct.setMinimumSize(new java.awt.Dimension(80, 80));
        buttonProduct.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProductActionPerformed(evt);
            }
        });
        jPanel3.add(buttonProduct);

        buttonClean.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonClean.setText("C");
        buttonClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClean.setMaximumSize(new java.awt.Dimension(80, 80));
        buttonClean.setMinimumSize(new java.awt.Dimension(80, 80));
        buttonClean.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCleanActionPerformed(evt);
            }
        });
        jPanel3.add(buttonClean);

        buttonZero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonZero.setText("0");
        buttonZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonZero.setMaximumSize(new java.awt.Dimension(80, 80));
        buttonZero.setMinimumSize(new java.awt.Dimension(80, 80));
        buttonZero.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });
        jPanel3.add(buttonZero);

        buttonEquals.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonEquals.setText("=");
        buttonEquals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEquals.setMaximumSize(new java.awt.Dimension(80, 80));
        buttonEquals.setMinimumSize(new java.awt.Dimension(80, 80));
        buttonEquals.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });
        jPanel3.add(buttonEquals);

        buttonDivision.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonDivision.setText("/");
        buttonDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDivision.setMaximumSize(new java.awt.Dimension(80, 80));
        buttonDivision.setMinimumSize(new java.awt.Dimension(80, 80));
        buttonDivision.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivisionActionPerformed(evt);
            }
        });
        jPanel3.add(buttonDivision);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        currentInput += "1";
        display.setText(currentInput);
    }//GEN-LAST:event_button1ActionPerformed
    
    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        currentInput += "7";
        display.setText(currentInput);
    }//GEN-LAST:event_button7ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        currentInput += "2";
        display.setText(currentInput);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        currentInput += "3";
        display.setText(currentInput);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        currentInput += "4";
        display.setText(currentInput);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        currentInput += "5";
        display.setText(currentInput);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        currentInput += "6";
        display.setText(currentInput);
    }//GEN-LAST:event_button6ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        currentInput += "8";
        display.setText(currentInput);
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        currentInput += "9";
        display.setText(currentInput);
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        if (!currentInput.isEmpty()){
            firstNumber = Double.parseDouble(currentInput);
            operator = "+";
            currentInput = "";
            display.setText("+");
        }
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        if (!currentInput.isEmpty()){
            firstNumber = Double.parseDouble(currentInput);
            operator = "-";
            currentInput = "";
            display.setText("-");
        }    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProductActionPerformed
        if (!currentInput.isEmpty()){
            firstNumber = Double.parseDouble(currentInput);
            operator = "*";
            currentInput = "";
            display.setText("*");
        }    }//GEN-LAST:event_buttonProductActionPerformed

    private void buttonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivisionActionPerformed
        if (!currentInput.isEmpty()){
            firstNumber = Double.parseDouble(currentInput);
            operator = "/";
            currentInput = "";
            display.setText("/");
        }    }//GEN-LAST:event_buttonDivisionActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed
        if (!currentInput.isEmpty() && !operator.isEmpty()) {
            double secondNumber = Double.parseDouble(currentInput);
            double result = 0;
            
            switch (operator) {
                case "+": result = firstNumber + secondNumber; break;
                case "-": result = firstNumber - secondNumber; break;
                case "*": result = firstNumber * secondNumber; break;
                case "/": result = firstNumber / secondNumber; break;
            }
            
            display.setText(String.valueOf(result));
            currentInput = String.valueOf(result);
            operator = "";
        }
    }//GEN-LAST:event_buttonEqualsActionPerformed

    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZeroActionPerformed
        currentInput += "0";
        display.setText(currentInput);
    }//GEN-LAST:event_buttonZeroActionPerformed

    private void buttonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCleanActionPerformed
        currentInput = "";
        operator = "";
        firstNumber = 0;
        display.setText("");
    }//GEN-LAST:event_buttonCleanActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        display.setText(currentInput);
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonClean;
    private javax.swing.JButton buttonDivision;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonProduct;
    private javax.swing.JButton buttonZero;
    private javax.swing.JTextField display;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
